[package]
name = "no_inflate"
version = "0.1.0"
edition = "2021"

[lib]
name = "no_inflate"
path = "src/lib.rs"
crate-type = ["rlib", "cdylib"]

[dependencies]

[features]
default = []
alloc = []

[dev-dependencies]
flate2 = { version = "1.0", features = ["zlib"] }
wee_alloc = "0.4"
